### ISSUE TITLE
Proposal: Websocket emulation server & transport

### ISSUE THREAD

**Issue by awill1988** [versatica/protoo#12]
Appreciate everything the group has done.

It seems like this project is evolving into a nice alternative to socket.io for a websocket transport.

I'm not sure what the roadmap looks like in regards to adding other sorts of servers/transports (similar to SocksJS), but if there's any way to add this into this library, it would be useful.

Having something like:
```
  const protooXhrPollingServer = new protoo.XhrPollingServer(httpServer, options);
```

would be awesome.. Thanks for your time!

**Comment by ibc** [comment]
Honestly I don't want to make the effort to implement "HTTP polling" transport. As far as I understand, polling is just implemented by other libraries just to allow them work in browsers without WebSocket support. I see no other benefit at all. And I do not want to replicate it just because socket.io does it.

If there is any other reason to implement it, please comment. However, as said above, I won't make the big effort.
